name: kirigami
channels:
  - conda-forge
dependencies:
  - python=3.11
  - ffmpeg
  - libxkbcommon
  - libxcb
  - xcb-util-cursor
  - xcb-util-wm
  - xcb-util-keysyms
  - xcb-util-image
  - xcb-util-renderutil
  - xkeyboard-config
  - pyyaml
  - numpy
  - scipy>=1.11,<2
  - pip
  - pip:
      - PySide6
      - opencv-python-headless
      - trimesh>=5.1,<6
